{% set name = "luv" %}
{% set version = "1.48.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/luvit/{{ name }}/archive/{{ version }}-2.tar.gz
  sha256: e64cd8a0197449288b37df6ca058120e8d2308fc305f543162b5bf3e92273a05

build:
  number: 0
  run_exports:
  - {{ pin_subpackage('luv', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - lua-compat-5.3-c
    - make  # [unix]
    - ninja  # [win]
  host:
    - libuv
    - luajit-openresty
  run:
    - luajit-openresty  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libluv${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/luvit/{{ name }}
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Bare libuv bindings for lua
  dev_url: https://github.com/luvit/{{ name }}

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
